/*
 * This file is generated by jOOQ.
 */
package com.cas.easycas.dao.tables;


import com.cas.easycas.dao.Indexes;
import com.cas.easycas.dao.Keys;
import com.cas.easycas.dao.Public;
import com.cas.easycas.dao.tables.records.AdRuleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdRule extends TableImpl<AdRuleRecord> {

    private static final long serialVersionUID = 922214507;

    /**
     * The reference instance of <code>public.ad_rule</code>
     */
    public static final AdRule AD_RULE = new AdRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdRuleRecord> getRecordType() {
        return AdRuleRecord.class;
    }

    /**
     * The column <code>public.ad_rule.id</code>.
     */
    public final TableField<AdRuleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ad_rule_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ad_rule.chain_id</code>.
     */
    public final TableField<AdRuleRecord, Long> CHAIN_ID = createField("chain_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ad_rule.created_at</code>.
     */
    public final TableField<AdRuleRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.ad_rule.updated_at</code>.
     */
    public final TableField<AdRuleRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.ad_rule</code> table reference
     */
    public AdRule() {
        this(DSL.name("ad_rule"), null);
    }

    /**
     * Create an aliased <code>public.ad_rule</code> table reference
     */
    public AdRule(String alias) {
        this(DSL.name(alias), AD_RULE);
    }

    /**
     * Create an aliased <code>public.ad_rule</code> table reference
     */
    public AdRule(Name alias) {
        this(alias, AD_RULE);
    }

    private AdRule(Name alias, Table<AdRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private AdRule(Name alias, Table<AdRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AdRule(Table<O> child, ForeignKey<O, AdRuleRecord> key) {
        super(child, key, AD_RULE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AD_RULE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AdRuleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AD_RULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AdRuleRecord> getPrimaryKey() {
        return Keys.AD_RULE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AdRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<AdRuleRecord>>asList(Keys.AD_RULE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AdRuleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AdRuleRecord, ?>>asList(Keys.AD_RULE__AD_RULE_CHAIN_ID_FKEY);
    }

    public AuthChain authChain() {
        return new AuthChain(this, Keys.AD_RULE__AD_RULE_CHAIN_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdRule as(String alias) {
        return new AdRule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdRule as(Name alias) {
        return new AdRule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdRule rename(String name) {
        return new AdRule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdRule rename(Name name) {
        return new AdRule(name, null);
    }
}
