/*
 * This file is generated by jOOQ.
 */
package com.cas.easycas.dao.tables;


import com.cas.easycas.dao.Indexes;
import com.cas.easycas.dao.Keys;
import com.cas.easycas.dao.Public;
import com.cas.easycas.dao.tables.records.FidoRuleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FidoRule extends TableImpl<FidoRuleRecord> {

    private static final long serialVersionUID = 363294965;

    /**
     * The reference instance of <code>public.fido_rule</code>
     */
    public static final FidoRule FIDO_RULE = new FidoRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FidoRuleRecord> getRecordType() {
        return FidoRuleRecord.class;
    }

    /**
     * The column <code>public.fido_rule.id</code>.
     */
    public final TableField<FidoRuleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('fido_rule_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.fido_rule.chain_id</code>.
     */
    public final TableField<FidoRuleRecord, Long> CHAIN_ID = createField("chain_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fido_rule.created_at</code>.
     */
    public final TableField<FidoRuleRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.fido_rule.updated_at</code>.
     */
    public final TableField<FidoRuleRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.fido_rule</code> table reference
     */
    public FidoRule() {
        this(DSL.name("fido_rule"), null);
    }

    /**
     * Create an aliased <code>public.fido_rule</code> table reference
     */
    public FidoRule(String alias) {
        this(DSL.name(alias), FIDO_RULE);
    }

    /**
     * Create an aliased <code>public.fido_rule</code> table reference
     */
    public FidoRule(Name alias) {
        this(alias, FIDO_RULE);
    }

    private FidoRule(Name alias, Table<FidoRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private FidoRule(Name alias, Table<FidoRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FidoRule(Table<O> child, ForeignKey<O, FidoRuleRecord> key) {
        super(child, key, FIDO_RULE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FIDO_RULE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FidoRuleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FIDO_RULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FidoRuleRecord> getPrimaryKey() {
        return Keys.FIDO_RULE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FidoRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<FidoRuleRecord>>asList(Keys.FIDO_RULE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FidoRuleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FidoRuleRecord, ?>>asList(Keys.FIDO_RULE__FIDO_RULE_CHAIN_ID_FKEY);
    }

    public AuthChain authChain() {
        return new AuthChain(this, Keys.FIDO_RULE__FIDO_RULE_CHAIN_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FidoRule as(String alias) {
        return new FidoRule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FidoRule as(Name alias) {
        return new FidoRule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FidoRule rename(String name) {
        return new FidoRule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FidoRule rename(Name name) {
        return new FidoRule(name, null);
    }
}
