/*
 * This file is generated by jOOQ.
 */
package com.cas.easycas.dao.tables.records;


import com.cas.easycas.dao.tables.RootCertificate;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RootCertificateRecord extends UpdatableRecordImpl<RootCertificateRecord> implements Record15<Integer, Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1034065137;

    /**
     * Setter for <code>public.root_certificate.id</code>.
     */
    public RootCertificateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.root_certificate.company_id</code>.
     */
    public RootCertificateRecord setCompanyId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.company_id</code>.
     */
    public Long getCompanyId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.root_certificate.name</code>.
     */
    public RootCertificateRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.root_certificate.common_name</code>.
     */
    public RootCertificateRecord setCommonName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.common_name</code>.
     */
    public String getCommonName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.root_certificate.organization</code>.
     */
    public RootCertificateRecord setOrganization(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.organization</code>.
     */
    public String getOrganization() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.root_certificate.organizational_unit</code>.
     */
    public RootCertificateRecord setOrganizationalUnit(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.organizational_unit</code>.
     */
    public String getOrganizationalUnit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.root_certificate.locality</code>.
     */
    public RootCertificateRecord setLocality(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.locality</code>.
     */
    public String getLocality() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.root_certificate.state</code>.
     */
    public RootCertificateRecord setState(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.state</code>.
     */
    public String getState() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.root_certificate.country_name</code>.
     */
    public RootCertificateRecord setCountryName(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.country_name</code>.
     */
    public String getCountryName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.root_certificate.email</code>.
     */
    public RootCertificateRecord setEmail(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.root_certificate.root_certificate</code>.
     */
    public RootCertificateRecord setRootCertificate(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.root_certificate</code>.
     */
    public String getRootCertificate() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.root_certificate.is_enforced</code>.
     */
    public RootCertificateRecord setIsEnforced(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.is_enforced</code>.
     */
    public Boolean getIsEnforced() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.root_certificate.is_default</code>.
     */
    public RootCertificateRecord setIsDefault(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.is_default</code>.
     */
    public Boolean getIsDefault() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.root_certificate.created_at</code>.
     */
    public RootCertificateRecord setCreatedAt(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>public.root_certificate.updated_at</code>.
     */
    public RootCertificateRecord setUpdatedAt(Timestamp value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.root_certificate.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RootCertificate.ROOT_CERTIFICATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RootCertificate.ROOT_CERTIFICATE.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RootCertificate.ROOT_CERTIFICATE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RootCertificate.ROOT_CERTIFICATE.COMMON_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RootCertificate.ROOT_CERTIFICATE.ORGANIZATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RootCertificate.ROOT_CERTIFICATE.ORGANIZATIONAL_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return RootCertificate.ROOT_CERTIFICATE.LOCALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return RootCertificate.ROOT_CERTIFICATE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return RootCertificate.ROOT_CERTIFICATE.COUNTRY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return RootCertificate.ROOT_CERTIFICATE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return RootCertificate.ROOT_CERTIFICATE.ROOT_CERTIFICATE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return RootCertificate.ROOT_CERTIFICATE.IS_ENFORCED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return RootCertificate.ROOT_CERTIFICATE.IS_DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return RootCertificate.ROOT_CERTIFICATE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return RootCertificate.ROOT_CERTIFICATE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCommonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOrganizationalUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLocality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getRootCertificate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getIsEnforced();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getIsDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCommonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOrganizationalUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLocality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRootCertificate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsEnforced();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getIsDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value2(Long value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value4(String value) {
        setCommonName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value5(String value) {
        setOrganization(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value6(String value) {
        setOrganizationalUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value7(String value) {
        setLocality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value8(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value9(String value) {
        setCountryName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value10(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value11(String value) {
        setRootCertificate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value12(Boolean value) {
        setIsEnforced(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value13(Boolean value) {
        setIsDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value14(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord value15(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RootCertificateRecord values(Integer value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Boolean value12, Boolean value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RootCertificateRecord
     */
    public RootCertificateRecord() {
        super(RootCertificate.ROOT_CERTIFICATE);
    }

    /**
     * Create a detached, initialised RootCertificateRecord
     */
    public RootCertificateRecord(Integer id, Long companyId, String name, String commonName, String organization, String organizationalUnit, String locality, String state, String countryName, String email, String rootCertificate, Boolean isEnforced, Boolean isDefault, Timestamp createdAt, Timestamp updatedAt) {
        super(RootCertificate.ROOT_CERTIFICATE);

        set(0, id);
        set(1, companyId);
        set(2, name);
        set(3, commonName);
        set(4, organization);
        set(5, organizationalUnit);
        set(6, locality);
        set(7, state);
        set(8, countryName);
        set(9, email);
        set(10, rootCertificate);
        set(11, isEnforced);
        set(12, isDefault);
        set(13, createdAt);
        set(14, updatedAt);
    }
}
